[package]
name = "rproxy"
edition = "2021"
publish = false

[dependencies]
bytes = { version = "1.7.2", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
http = { version = "1.1.0", default-features = false }
http-body-util = { version = "0.1.2", default-features = false }
hyper = { version = "1.5.0", default-features = false, features = ["client", "server", "http1"] }
hyper-util = { version = "0.1.9", default-features = false, features = ["tokio"] }
regex = { version = "1.11.0", default-features = false }
tokio = { version = "1.40.0", default-features = false, features = ["fs", "rt", "rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.12", default-features = false, features = ["io-util"] }

[profile.release]
debug = false
panic = "abort"
strip = true