[package]
name = "rproxy"
edition = "2021"
publish = false

[dependencies]
bytes = { version = "1.7.2" }
http = { version = "1.1.0" }
http-body-util = { version = "0.1.2" }
hyper = { version = "1.5.0", features = ["full"] }
hyper-util = { version = "0.1.9", features = ["full"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = "0.7.10"
futures-util = "0.3.30"