[package]
name = "rproxy"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", default-features = false, features = ["fs", "io-util", "net", "macros", "rt-multi-thread"]}

[profile.release]
debug = false
panic = "abort"
strip = true