[package]
name = "rproxy"
edition = "2021"
publish = false

[dependencies]
bytes = { version = "1.5.0" }
http = { version = "1.1.0" }
http-body-util = { version = "0.1" }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }